# Background and foreground colors
background = #0c151a
foreground = #bebebe

# Standard colors
palette = 0=#0c151a
palette = 1=#f7312e
palette = 2=#31722b
palette = 3=#fbf695
palette = 4=#d99f15
palette = 5=#f0c37b
palette = 6=#b9b48e
palette = 7=#bebebe

# Bright colors
palette = 8=#8a8a8d
palette = 9=#f61f39
palette = 10=#33722b
palette = 11=#fbf695
palette = 12=#FFC107
palette = 13=#f0c37b
palette = 14=#b9b48e
palette = 15=#ffffff
