background            #0c151a
foreground            #bebebe

# black
color0  #0c151a
color8  #8a8a8d

# red
color1  #f7312e
color9  #f61f39

# green
color2  #31722b
color10 #33722b

# yellow
color3  #fbf695
color11 #fbf695

# blue
color4  #d99f15
color12 #FFC107

# magenta
color5  #f0c37b
color13 #f0c37b

#cyan
color6  #b9b48e
color14 #b9b48e

#white
color7  #bebebe
color15 #ffffff


