$terminal = kitty 
$menu = tofi-drun

# Hold Super and drag with left mouse button
bindm = SUPER, mouse:272, movewindow

# Keybinds
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, M, exit
bind = SUPER, W, killactive
bind = SUPER SHIFT, F, exec, kitty -e yazi
bind = SUPER, SPACE, exec, $menu
bind = SUPER SHIFT, N, exec, kitty -e nvim
bind = SUPER SHIFT, A, exec, gtk-launch chatgpt
bind = SUPER SHIFT, X, exec, gtk-launch x
bind = SUPER CTRL, B, exec, kitty --class float -e bluetui
bind = SUPER CTRL, X, exec, kitty --class float -e wifitui
bind = SUPER SHIFT, J, exec, eclipse
bind = SUPER CTRL, M, exec, ~/.local/bin/toggle-touchpad
bind = SUPER SHIFT, S, exec, spotify-launcher
bind = SUPER SHIFT, L, exec, kitty -e spotatui
bind = SUPER CTRL, V, exec, kitty --class float -e vpn-connect
bind = SUPER CTRL, P, exec, kitty -e eat-food
bind = SUPER CTRL, G, exec, ~/.local/bin/brightness-lower

bind = SUPER, T, togglefloating
bind = SUPER, F, fullscreen

bind = SUPER, h, movefocus, l 
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, J, movewindow, d
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, L, movewindow, r

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5

bind = SUPER CTRL, T, exec, kitty --class float -e btop 
bind = SUPER SHIFT, E, exec, chromium




# Volume
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl  = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bindel = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPause, exec, playerctl pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioStop, exec, playerctl stop

bind = , XF86Launch7, exec, grim -g "$(slurp)" - | wl-copy --type image/png
bind = SHIFT, XF86Launch7, exec, grim - | wl-copy --type image/png

bind = , XF86Calculator, exec, gnome-calculator
bind = , XF86Explorer, exec, thunar
bind = , XF86HomePage, exec, xdg-open https://google.com

windowrule = match:class ^float$, float on, center on, size 1000 700
