source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/aether/theme/hyprland.conf
source = ~/.config/hypr/yazi.conf

# Comment out following to use aether theme
$activeBorderColor = rgb(ffffff)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
}

env = EDITOR, nvim
env = VISUAL, nvim

exec-once = waybar
exec-once = nm-applet --indicator
exec-once = swaybg -i ~/.config/aether/theme/backgrounds/*.jpg -m fill

input {
  repeat_rate = 80
  repeat_delay = 180
	kb_layout = us
	follow_mouse = 1

	touchpad { 
		natural_scroll = no 
		tap-to-click = yes
	}


  kb_options = altwin:swap_alt_win
}


general {
	gaps_in = 2
	gaps_out = 4
	border_size = 1
	resize_on_border = true
}

decoration {
	# rounding = 8
}

animations {
	enabled = no
}




